Repository Bookhive-Club/Bookhive-Client, pull requests merged in 2023-10, with the labels that each got.

#13 Reduced the size of sign up page now there is no scrolling
  src/app/auth/otp/page.tsx
  src/app/auth/password/forgotten-password/page.tsx
  src/app/auth/password/reset-password/page.tsx
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/components/atom/form/inputArea.tsx
  src/components/templates/home/layouts/auth/authLayout.tsx
Labels: hacktoberfest-accepted

#14 Removed phone number input and brought back old size
  src/app/auth/signup/page.tsx
  src/components/atom/form/inputArea.tsx
  src/components/templates/home/layouts/auth/authLayout.tsx
  src/validations/auth/signupValidationSchema.ts
Labels: hactoberfest, hactoberfest-2023, hactoberfest-accept, hacktoberfest-accepted

#15 Added Issue while referring to Contribution Guidelines. #12
  CONTRBUTING.md
  README.md
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accept, hacktoberfest-accepted

#20 fixing center authLayout.tsx responsively
  src/layouts/auth/authLayout.tsx
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#25 [feat]: Add a preloader issue #16
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/atom/home/header.tsx
  src/components/preloader/Preloader.tsx
  tsconfig.json
  yarn.lock
Labels: hacktoberfest, hacktoberfest-2023, hacktoberfest-accept, hacktoberfest-accepted
